### ISSUE TITLE
couldn't find "libimojigraphics.so"

### ISSUE THREAD

**Issue by UrK** [imojiengineering/imoji-android-sdk-ui#9]
The application crashes (I have no idea where) with the following exception. Occurs on multiple devices and on Android versions 4-6.

`Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xxx.yyy.app-1/base.apk"],nativeLibraryDirectories=[/data/app/xxx.yyy.app-1/lib/arm64, /data/app/xxx.yyy.app-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libimojigraphics.so"
       at java.lang.Runtime.loadLibrary(Runtime.java:367)
       at java.lang.System.loadLibrary(System.java:1076)
       at io.imoji.sdk.graphics.IG.(IG.java:33)
       at io.imoji.sdk.graphics.IGEditorView.resetEditor(IGEditorView.java:221)
       at io.imoji.sdk.graphics.IGEditorView.access$600(IGEditorView.java:46)
       at io.imoji.sdk.graphics.IGEditorView$8.run(IGEditorView.java:293)
       at io.imoji.sdk.graphics.IGEditorView.onDrawFrame(IGEditorView.java:101)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1649)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1354)
`

**Comment by DoubleRockStar** [comment]
compile is successful, but run time crash issue occurred.  Android Studio 2.1.2 , AVD api level 24.
at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                               at java.lang.System.loadLibrary(System.java:1530)
                                                                               at io.imoji.sdk.graphics.IG.<clinit>(IG.java:33)
                                                                               at io.imoji.sdk.graphics.IGEditorView.resetEditor(IGEditorView.java:221)
                                                                               at io.imoji.sdk.graphics.IGEditorView.access$600(IGEditorView.java:46)
                                                                               at io.imoji.sdk.graphics.IGEditorView$8.run(IGEditorView.java:293)
                                                                               at io.imoji.sdk.graphics.IGEditorView.onDrawFrame(IGEditorView.java:101)
                                                                               at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1553)
                                                                               at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)

**Comment by thor-the-norseman** [comment]
Something seems to have broken my NDK C code. If my services are needed, please inform your manager.

**Comment by UrK** [comment]
Ok... it seems like this happens on starting image editing

**Comment by DoubleRockStar** [comment]
I solved the crash issue by adding following codes in gradle.

defaultConfig {
        applicationId "com.tahaclay.gifselfiecam"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"

        // this is for targeting custom libs for 32 bit core when you have not prepared 64 bit
        ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86"//, "mips"
        }
    }

**Comment by UrK** [comment]
@DoubleRockStar, your solution worked. Though, I have no idea what it does. Won't it harm 64-bit devices?

**Comment by DoubleRockStar** [comment]
I think it will be fine for 64-bit as well

**Comment by sergeychilingaryan** [comment]
could you please add arm64-v8a libs as well ?
